name: "My Bunny"
description: "Suivi du lapin - santé, poids, vétérinaire et température"
version: "1.0.0"
slug: "my-bunny"
init: false
arch:
  - aarch64
  - amd64
ports:
  4000/tcp: 4000
ports_description:
  4000/tcp: "Interface web My Bunny"
map:
  - share:rw
