name: "Epargne"
description: "Suivi de portefeuille personnel"
version: "1.0.0"
slug: "epargne"
init: false
arch:
  - aarch64
  - amd64
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Interface web"
map:
  - share:rw
